network.host: 0.0.0.0
path:
   logs: /usr/share/elasticsearch/logs
   data: /usr/share/elasticsearch/data
   repo: /usr/share/elasticsearch/snapshots
   scripts: /usr/share/elasticsearch/scripts
cluster:
   name: check-app-cluster
node:
   name: check-app-node
http:
   cors:
      enabled:        true
      allow-origin:   '*'